### ISSUE TITLE
Update the rick_trans.txt 

### ISSUE THREAD

**Issue by Abhiram970** [Abhiram970/RickBot#2]
The rick_trans has dialogues of rick and morty season 1 , it would be nice to add more seasons worth of transcript , it's available in transcript wiki , you need to paste dialogues in the same way as given in the txt file so that parse script.ipynb would work.

**Comment by Aron-R** [comment]
I would like to be assigned this

**Comment by Abhiram970** [comment]
@Aron-R  you can do it :)
